### ISSUE TITLE
Request to share the code

### ISSUE THREAD

**Issue by mayurmallya** [lzrobots/DGCNet#4]
Hi authors,

Could you please share the code for this paper?

Thank you

**Comment by mohaEs** [comment]
I found something here:
https://github.com/lxtGH/GALD-Net

**Comment by lxtGH** [comment]
@mohaEs @mayurmallya As co-auther, I will release code and model in another repo as soon as possible. https://github.com/lxtGH/GALD-Net. Please keep tuned.

**Comment by lxtGH** [comment]
The code and models have been released.
